using System.Globalization;
using IncidentManager.Application.Reporting;
using MigraDoc.DocumentObjectModel;
using MigraDoc.Rendering;
using PdfSharp.Fonts;

namespace IncidentManager.Infrastructure.Reporting;

public sealed partial class ReportGenerator
{
    private static readonly Color Slate = new(0x44, 0x54, 0x6A); // heading colour matching the house template

    static ReportGenerator()
    {
        // Serve fonts from embedded resources (not the OS), so PDF generation works identically on
        // Windows, Linux (CI), and Windows Server Core — see EmbeddedFontResolver.
        if (GlobalFontSettings.FontResolver is null)
            GlobalFontSettings.FontResolver = new EmbeddedFontResolver();
    }

    public byte[] GeneratePdf(CaseReportModel m)
    {
        var doc = new Document();
        var normal = doc.Styles["Normal"]!;
        normal.Font.Name = "DejaVu Sans";
        normal.Font.Size = 9;

        // MigraDoc loads header images from a file path (its in-memory source handling is unreliable
        // across formats); stage the logo to a temp file for the duration of the render, then clean up.
        var logoPath = StageLogo(m);

        var section = doc.AddSection();
        section.PageSetup.LeftMargin = Unit.FromCentimeter(2);
        section.PageSetup.RightMargin = Unit.FromCentimeter(2);
        section.PageSetup.HeaderDistance = Unit.FromCentimeter(1);
        section.PageSetup.FooterDistance = Unit.FromCentimeter(1);
        // The header (org/team, plus an optional ~1.2cm logo) lives in the top margin — widen it so the
        // body clears the header instead of printing under it.
        section.PageSetup.TopMargin = Unit.FromCentimeter(logoPath is not null ? 4.2 : 2.8);
        try
        {
            BuildHeaderFooter(section, m, logoPath);

            // Title + at-a-glance facts (always present).
            var title = section.AddParagraph($"{m.CaseNumber} — {m.Title}");
            title.Format.Font.Bold = true;
            title.Format.Font.Size = 16;
            title.Format.SpaceAfter = Unit.FromCentimeter(0.2);
            AppendFacts(section, m);

            foreach (var s in m.Sections)
                RenderSection(section, s, m);

            // Integrity provenance stamp — always rendered.
            var footer = section.AddParagraph($"Generated by {m.GeneratedBy} at {m.GeneratedAtUtc:u}. Case content hash: {m.ContentHash}");
            footer.Format.Font.Italic = true;
            footer.Format.Font.Size = 7;
            footer.Format.SpaceBefore = Unit.FromCentimeter(0.5);

            var renderer = new PdfDocumentRenderer { Document = doc };
            renderer.RenderDocument();

            using var ms = new MemoryStream();
            renderer.PdfDocument.Save(ms);
            return ms.ToArray();
        }
        finally
        {
            if (logoPath is not null) { try { File.Delete(logoPath); } catch { /* best effort */ } }
        }
    }

    private static string? StageLogo(CaseReportModel m)
    {
        if (m.LogoBytes is not { Length: > 0 }) return null;
        var isPng = (m.LogoContentType ?? "").Contains("png", StringComparison.OrdinalIgnoreCase);
        var path = Path.Combine(Path.GetTempPath(), $"casebook-logo-{Guid.NewGuid():N}{(isPng ? ".png" : ".jpg")}");
        try { File.WriteAllBytes(path, m.LogoBytes); return path; }
        catch { return null; }
    }

    private static void RenderSection(Section section, ReportSection which, CaseReportModel m)
    {
        switch (which)
        {
            case ReportSection.Summary:
                Heading(section, "Summary");
                section.AddParagraph(string.IsNullOrWhiteSpace(m.Summary) ? "(not provided)" : m.Summary);
                break;

            case ReportSection.BusinessImpact:
                Heading(section, "Business Impact");
                AppendBusinessImpact(section, m);
                break;

            case ReportSection.EventTimeline:
                Heading(section, "Event Timeline");
                Caption(section, "The reconstructed adversary activity, in order — ATT&CK tactic(s), actor → target, and technique.");
                PdfTable(section, ["#", "When (UTC)", "Tactic(s)", "Actor → Target", "Technique", "What happened"],
                    m.AttackChain.Select(x => new[]
                    {
                        x.Order.ToString(CultureInfo.InvariantCulture),
                        x.OccurredAtUtc.ToString("u"),
                        x.Tactics,
                        string.IsNullOrEmpty(x.Actor) && string.IsNullOrEmpty(x.Target) ? "" : $"{x.Actor} → {x.Target}",
                        x.TechniqueId ?? "",
                        x.Description
                    }).ToList(),
                    [0.8, 2.6, 2.6, 3.0, 1.8, 5.2]);
                break;

            case ReportSection.InvestigationTimeline:
                Heading(section, "Investigation Timeline");
                Caption(section, "Analyst and team actions.");
                PdfTable(section, ["When (UTC)", "Type", "Description", "Source"],
                    m.InvestigationTimeline.Select(x => new[] { x.OccurredAtUtc.ToString("u"), x.Type, x.Description, x.Source ?? "" }).ToList(),
                    [2.8, 2.2, 8.0, 3.0]);
                break;

            case ReportSection.SystemsReviewed:
                Heading(section, "Systems Reviewed");
                Caption(section, "Entities and indicators examined during the investigation.");
                if (!string.IsNullOrWhiteSpace(m.ImpactedAssets))
                    section.AddParagraph($"Impacted assets: {m.ImpactedAssets}");
                PdfTable(section, ["Type", "Value", "Label", "Disposition", "Source"],
                    m.Entities.Select(x => new[] { x.Type, x.Value, x.Label ?? "", x.Disposition, x.Source ?? "" }).ToList(),
                    [2.6, 5.0, 2.6, 2.2, 2.6]);
                break;

            case ReportSection.Recommendations:
                Heading(section, "Recommendations");
                Caption(section, "After-action items and follow-up tasks.");
                PdfTable(section, ["Task", "Owner", "Due (UTC)", "Status"],
                    m.ActionItems.Select(x => new[] { x.Title, x.Owner ?? "", x.DueAtUtc?.ToString("u") ?? "", x.Status }).ToList(),
                    [8.0, 3.0, 2.5, 2.5]);
                break;

            case ReportSection.Outcome:
                Heading(section, "Outcome");
                AppendOutcome(section, m);
                break;

            case ReportSection.Appendix:
                Heading(section, "Appendix");
                AppendAppendix(section, m);
                break;
        }
    }

    private static void AppendFacts(Section section, CaseReportModel m)
    {
        section.AddParagraph($"Classification: {m.Classification}    Phase: {m.Phase}    Severity: {m.Severity}");
        section.AddParagraph($"Origin: {m.Origin}{(m.VendorName is null ? "" : $" ({m.VendorName})")}");
        if (m.DetectionCaseId is not null) section.AddParagraph($"Detection case: {m.DetectionCaseId}");
        if (m.DataTypesInvolved is not null) section.AddParagraph($"Data types involved: {m.DataTypesInvolved}");
        if (m.LegalReferred) section.AddParagraph($"Legal/Privacy referral recorded. {m.LegalNote}");
    }

    private static void AppendBusinessImpact(Section section, CaseReportModel m)
    {
        var any = false;
        if (m.AffectedIndividualsCount is { } n) { section.AddParagraph($"Affected individuals: {n:N0}"); any = true; }
        if (m.DataElementsSummary is not null) { section.AddParagraph($"Data elements: {m.DataElementsSummary}"); any = true; }
        if (m.NotificationTriggersSummary is not null) { section.AddParagraph($"Notification triggers: {m.NotificationTriggersSummary}"); any = true; }
        if (!string.IsNullOrWhiteSpace(m.AffectedStates)) { section.AddParagraph($"Affected jurisdictions: {m.AffectedStates}"); any = true; }
        if (!string.IsNullOrWhiteSpace(m.ImpactedAssets)) { section.AddParagraph($"Impacted assets: {m.ImpactedAssets}"); any = true; }
        if (m.DataTypesInvolved is not null) { section.AddParagraph($"Data types involved: {m.DataTypesInvolved}"); any = true; }
        if (m.LegalReferred) { section.AddParagraph($"Legal/Privacy referral recorded. {m.LegalNote}"); any = true; }
        if (!any) section.AddParagraph("(no impact assessment recorded)");
    }

    private static void AppendOutcome(Section section, CaseReportModel m)
    {
        section.AddParagraph($"Current phase: {m.Phase}. Classification: {m.Classification}. Severity: {m.Severity}.");
        void Stamp(string label, DateTimeOffset? at) { if (at is { } v) section.AddParagraph($"{label}: {v:u}"); }
        Stamp("Detected", m.DetectedAtUtc);
        Stamp("Contained", m.ContainedAtUtc);
        Stamp("Resolved", m.ResolvedAtUtc);
        Stamp("Closed", m.ClosedAtUtc);
        if (m.LegalReferred) section.AddParagraph($"Referred to Legal/Privacy. {m.LegalNote}");
    }

    private static void AppendAppendix(Section section, CaseReportModel m)
    {
        SubHeading(section, "A. Assignments");
        PdfTable(section, ["User", "Role"],
            m.Assignments.Select(x => new[] { x.User, x.Role }).ToList(),
            [8.0, 6.0]);

        SubHeading(section, "B. Entity relationships");
        PdfTable(section, ["Source", "Relationship", "Target", "Notes"],
            m.Relationships.Select(x => new[] { x.Source, x.Relationship, x.Target, x.Description ?? "" }).ToList(),
            [4.5, 3.0, 4.5, 3.0]);

        SubHeading(section, "C. MITRE ATT&CK techniques");
        PdfTable(section, ["Technique", "Name", "Tactic"],
            m.Techniques.Select(x => new[] { x.TechniqueId, x.Name, x.Tactic }).ToList(),
            [3.0, 8.0, 4.0]);

        SubHeading(section, "D. Classification history");
        PdfTable(section, ["When (UTC)", "From", "To", "Reason", "By"],
            m.ClassificationHistory.Select(x => new[] { x.AtUtc.ToString("u"), x.From, x.To, x.Reason, x.By }).ToList(),
            [2.8, 2.0, 2.0, 6.2, 3.0]);

        SubHeading(section, "E. Severity history");
        PdfTable(section, ["When (UTC)", "From", "To", "Reason", "By"],
            m.SeverityHistory.Select(x => new[] { x.AtUtc.ToString("u"), x.From, x.To, x.Reason, x.By }).ToList(),
            [2.8, 2.0, 2.0, 6.2, 3.0]);

        SubHeading(section, "F. Evidence index");
        PdfTable(section, ["File", "Size", "SHA-256", "Uploaded", "By"],
            m.Evidence.Select(x => new[] { x.FileName, x.SizeBytes.ToString(CultureInfo.InvariantCulture), x.Sha256, x.UploadedAtUtc.ToString("u"), x.UploadedBy }).ToList(),
            [3.0, 1.5, 6.5, 2.8, 2.2]);

        SubHeading(section, "G. Analyst notes");
        if (m.Notes.Count == 0) section.AddParagraph("(none)");
        foreach (var n in m.Notes)
        {
            var p = section.AddParagraph($"[{n.AtUtc:u}] {n.Author}");
            p.Format.Font.Bold = true;
            section.AddParagraph(n.Body);
        }
    }

    /// <summary>Branded header (logo over organisation/team name) + centred page-number footer.</summary>
    private static void BuildHeaderFooter(Section section, CaseReportModel m, string? logoPath)
    {
        var org = string.IsNullOrWhiteSpace(m.OrganizationName) ? "[Company Name]" : m.OrganizationName!;
        var team = string.IsNullOrWhiteSpace(m.TeamName) ? "[Team Name]" : m.TeamName!;
        var header = section.Headers.Primary;

        if (logoPath is not null)
        {
            try
            {
                var logoP = header.AddParagraph();
                logoP.Format.Alignment = ParagraphAlignment.Center;
                var img = logoP.AddImage(logoPath);
                img.Height = Unit.FromCentimeter(1.2);
                img.LockAspectRatio = true;
            }
            catch { /* text-only header if the image can't be embedded */ }
        }

        var orgP = header.AddParagraph(org);
        orgP.Format.Alignment = ParagraphAlignment.Center;
        orgP.Format.Font.Bold = true;
        orgP.Format.Font.Size = 11;

        var teamP = header.AddParagraph(team);
        teamP.Format.Alignment = ParagraphAlignment.Center;
        teamP.Format.Font.Size = 10;

        var pageP = section.Footers.Primary.AddParagraph();
        pageP.Format.Alignment = ParagraphAlignment.Center;
        pageP.AddPageField();
    }

    private static void Heading(Section section, string text, double size = 12)
    {
        var p = section.AddParagraph(text);
        p.Format.Font.Bold = true;
        p.Format.Font.Size = size;
        p.Format.Font.Underline = Underline.Single;
        p.Format.Font.Color = Slate;
        p.Format.SpaceBefore = Unit.FromCentimeter(0.35);
        p.Format.SpaceAfter = Unit.FromCentimeter(0.1);
    }

    private static void SubHeading(Section section, string text)
    {
        var p = section.AddParagraph(text);
        p.Format.Font.Bold = true;
        p.Format.Font.Size = 10;
        p.Format.Font.Color = Slate;
        p.Format.SpaceBefore = Unit.FromCentimeter(0.25);
        p.Format.SpaceAfter = Unit.FromCentimeter(0.05);
    }

    private static void Caption(Section section, string text) =>
        section.AddParagraph(text).Format.Font.Italic = true;

    private static void PdfTable(Section section, string[] headers, List<string[]> rows, double[] widthsCm)
    {
        var table = section.AddTable();
        table.Borders.Width = 0.5;
        for (var i = 0; i < headers.Length; i++)
            table.AddColumn(Unit.FromCentimeter(widthsCm[i]));

        var headerRow = table.AddRow();
        headerRow.Format.Font.Bold = true;
        for (var i = 0; i < headers.Length; i++)
            headerRow.Cells[i].AddParagraph(headers[i]);

        if (rows.Count == 0)
        {
            var r = table.AddRow();
            r.Cells[0].AddParagraph("(none)");
        }
        foreach (var row in rows)
        {
            var r = table.AddRow();
            for (var i = 0; i < headers.Length && i < row.Length; i++)
                r.Cells[i].AddParagraph(row[i] ?? "");
        }
    }
}
