using System.Globalization;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using IncidentManager.Application.Abstractions;
using IncidentManager.Application.Reporting;
using A = DocumentFormat.OpenXml.Drawing;
using DW = DocumentFormat.OpenXml.Drawing.Wordprocessing;
using PIC = DocumentFormat.OpenXml.Drawing.Pictures;

namespace IncidentManager.Infrastructure.Reporting;

/// <summary>
/// Produces the case report as an editable Word document (DocumentFormat.OpenXml) or a final PDF
/// (MigraDoc — see the .Pdf partial). Both render from the same <see cref="CaseReportModel"/>, so
/// the two formats stay in lock-step. The layout follows the house event-report template — a narrative
/// body (Summary, Business Impact, Event/Investigation Timeline, Systems Reviewed, Recommendations,
/// Outcome) with the full structured record in an Appendix — with a branded header/footer. Which body
/// sections appear, and their order, are administered via <see cref="ReportLayout"/>. All libraries are
/// MIT-licensed — no per-seat cost.
/// </summary>
public sealed partial class ReportGenerator : IReportGenerator
{
    /// <summary>Slate heading colour matching the house template.</summary>
    private const string HeadingColor = "44546A";

    public byte[] GenerateWord(CaseReportModel m)
    {
        using var ms = new MemoryStream();
        using (var doc = WordprocessingDocument.Create(ms, WordprocessingDocumentType.Document, true))
        {
            var main = doc.AddMainDocumentPart();
            main.Document = new Document();
            var body = main.Document.AppendChild(new Body());

            // Title + at-a-glance facts (always present).
            body.AppendChild(P($"{m.CaseNumber} — {m.Title}", bold: true, size: 32));
            AppendFacts(body, m);

            // Administered body sections, in the configured order.
            foreach (var section in m.Sections)
                RenderSection(body, section, m);

            // Integrity provenance stamp — always rendered, never toggleable.
            body.AppendChild(P(
                $"Generated by {m.GeneratedBy} at {m.GeneratedAtUtc:u}. Case content hash: {m.ContentHash}",
                italic: true, size: 16));

            // Branded header + page-number footer (must be appended as the final body child).
            AppendHeaderFooter(main, body, m);

            main.Document.Save();
        }
        return ms.ToArray();
    }

    private static void RenderSection(Body body, ReportSection section, CaseReportModel m)
    {
        switch (section)
        {
            case ReportSection.Summary:
                body.AppendChild(Heading("Summary"));
                body.AppendChild(P(string.IsNullOrWhiteSpace(m.Summary) ? "(not provided)" : m.Summary));
                break;

            case ReportSection.BusinessImpact:
                body.AppendChild(Heading("Business Impact"));
                AppendBusinessImpact(body, m);
                break;

            case ReportSection.EventTimeline:
                body.AppendChild(Heading("Event Timeline"));
                body.AppendChild(P("The reconstructed adversary activity, in order — MITRE ATT&CK tactic(s), actor → target, and technique.", italic: true, size: 18));
                body.AppendChild(WordTable(
                    ["#", "When (UTC)", "Tactic(s)", "Actor → Target", "Technique", "What happened"],
                    m.AttackChain.Select(x => new[]
                    {
                        x.Order.ToString(CultureInfo.InvariantCulture),
                        x.OccurredAtUtc.ToString("u"),
                        x.Tactics,
                        string.IsNullOrEmpty(x.Actor) && string.IsNullOrEmpty(x.Target) ? "" : $"{x.Actor} → {x.Target}",
                        x.TechniqueId ?? "",
                        x.Description
                    })));
                break;

            case ReportSection.InvestigationTimeline:
                body.AppendChild(Heading("Investigation Timeline"));
                body.AppendChild(P("Analyst and team actions.", italic: true, size: 18));
                body.AppendChild(WordTable(
                    ["When (UTC)", "Type", "Description", "Source"],
                    m.InvestigationTimeline.Select(x => new[] { x.OccurredAtUtc.ToString("u"), x.Type, x.Description, x.Source ?? "" })));
                break;

            case ReportSection.SystemsReviewed:
                body.AppendChild(Heading("Systems Reviewed"));
                body.AppendChild(P("Entities and indicators examined during the investigation.", italic: true, size: 18));
                if (!string.IsNullOrWhiteSpace(m.ImpactedAssets))
                    body.AppendChild(P($"Impacted assets: {m.ImpactedAssets}"));
                body.AppendChild(WordTable(
                    ["Type", "Value", "Label", "Disposition", "Source"],
                    m.Entities.Select(x => new[] { x.Type, x.Value, x.Label ?? "", x.Disposition, x.Source ?? "" })));
                break;

            case ReportSection.Recommendations:
                body.AppendChild(Heading("Recommendations"));
                body.AppendChild(P("After-action items and follow-up tasks.", italic: true, size: 18));
                body.AppendChild(WordTable(
                    ["Task", "Owner", "Due (UTC)", "Status"],
                    m.ActionItems.Select(x => new[] { x.Title, x.Owner ?? "", x.DueAtUtc?.ToString("u") ?? "", x.Status })));
                break;

            case ReportSection.Outcome:
                body.AppendChild(Heading("Outcome"));
                AppendOutcome(body, m);
                break;

            case ReportSection.Appendix:
                body.AppendChild(Heading("Appendix"));
                AppendAppendix(body, m);
                break;
        }
    }

    private static void AppendFacts(Body body, CaseReportModel m)
    {
        body.AppendChild(P($"Classification: {m.Classification}    Phase: {m.Phase}    Severity: {m.Severity}", size: 20));
        body.AppendChild(P($"Origin: {m.Origin}{(m.VendorName is null ? "" : $" ({m.VendorName})")}", size: 20));
        if (m.DetectionCaseId is not null) body.AppendChild(P($"Detection case: {m.DetectionCaseId}", size: 20));
        if (m.DataTypesInvolved is not null) body.AppendChild(P($"Data types involved: {m.DataTypesInvolved}", size: 20));
        if (m.LegalReferred) body.AppendChild(P($"Legal/Privacy referral recorded. {m.LegalNote}", size: 20));
        if (m.LegalHold) body.AppendChild(P("Legal hold in effect — case data must be preserved (do not delete).", size: 20));
    }

    private static void AppendBusinessImpact(Body body, CaseReportModel m)
    {
        var any = false;
        if (m.AffectedIndividualsCount is { } n) { body.AppendChild(P($"Affected individuals: {n:N0}")); any = true; }
        if (m.DataElementsSummary is not null) { body.AppendChild(P($"Data elements: {m.DataElementsSummary}")); any = true; }
        if (m.NotificationTriggersSummary is not null) { body.AppendChild(P($"Notification triggers: {m.NotificationTriggersSummary}")); any = true; }
        if (!string.IsNullOrWhiteSpace(m.AffectedStates)) { body.AppendChild(P($"Affected jurisdictions: {m.AffectedStates}")); any = true; }
        if (!string.IsNullOrWhiteSpace(m.ImpactedAssets)) { body.AppendChild(P($"Impacted assets: {m.ImpactedAssets}")); any = true; }
        if (m.DataTypesInvolved is not null) { body.AppendChild(P($"Data types involved: {m.DataTypesInvolved}")); any = true; }
        if (m.LegalReferred) { body.AppendChild(P($"Legal/Privacy referral recorded. {m.LegalNote}")); any = true; }
        if (m.LegalHold) { body.AppendChild(P("Legal hold in effect — case data must be preserved (do not delete).")); any = true; }
        if (!any) body.AppendChild(P("(no impact assessment recorded)"));
    }

    private static void AppendOutcome(Body body, CaseReportModel m)
    {
        body.AppendChild(P($"Current phase: {m.Phase}. Classification: {m.Classification}. Severity: {m.Severity}."));
        void Stamp(string label, DateTimeOffset? at) { if (at is { } v) body.AppendChild(P($"{label}: {v:u}")); }
        Stamp("Detected", m.DetectedAtUtc);
        Stamp("Contained", m.ContainedAtUtc);
        Stamp("Resolved", m.ResolvedAtUtc);
        Stamp("Closed", m.ClosedAtUtc);
        if (m.LegalReferred) body.AppendChild(P($"Referred to Legal/Privacy. {m.LegalNote}"));
        if (m.LegalHold) body.AppendChild(P("Legal hold in effect — case data must be preserved (do not delete)."));
    }

    private static void AppendAppendix(Body body, CaseReportModel m)
    {
        body.AppendChild(SubHeading("A. Assignments"));
        body.AppendChild(WordTable(["User", "Role"],
            m.Assignments.Select(x => new[] { x.User, x.Role })));

        body.AppendChild(SubHeading("B. Entity relationships"));
        body.AppendChild(WordTable(["Source", "Relationship", "Target", "Notes"],
            m.Relationships.Select(x => new[] { x.Source, x.Relationship, x.Target, x.Description ?? "" })));

        body.AppendChild(SubHeading("C. MITRE ATT&CK techniques"));
        body.AppendChild(WordTable(["Technique", "Name", "Tactic"],
            m.Techniques.Select(x => new[] { x.TechniqueId, x.Name, x.Tactic })));

        body.AppendChild(SubHeading("D. Classification history"));
        body.AppendChild(WordTable(["When (UTC)", "From", "To", "Reason", "By"],
            m.ClassificationHistory.Select(x => new[] { x.AtUtc.ToString("u"), x.From, x.To, x.Reason, x.By })));

        body.AppendChild(SubHeading("E. Severity history"));
        body.AppendChild(WordTable(["When (UTC)", "From", "To", "Reason", "By"],
            m.SeverityHistory.Select(x => new[] { x.AtUtc.ToString("u"), x.From, x.To, x.Reason, x.By })));

        body.AppendChild(SubHeading("F. Evidence index"));
        body.AppendChild(WordTable(["File", "Size (bytes)", "SHA-256", "Uploaded (UTC)", "By"],
            m.Evidence.Select(x => new[] { x.FileName, x.SizeBytes.ToString(CultureInfo.InvariantCulture), x.Sha256, x.UploadedAtUtc.ToString("u"), x.UploadedBy })));

        body.AppendChild(SubHeading("G. Analyst notes"));
        if (m.Notes.Count == 0) body.AppendChild(P("(none)"));
        foreach (var n in m.Notes)
        {
            body.AppendChild(P($"[{n.AtUtc:u}] {n.Author}", bold: true, size: 18));
            body.AppendChild(P(n.Body));
        }
    }

    private static Paragraph P(string text, bool bold = false, bool italic = false, int size = 22)
    {
        var runProps = new RunProperties();
        if (bold) runProps.Append(new Bold());
        if (italic) runProps.Append(new Italic());
        runProps.Append(new FontSize { Val = size.ToString(CultureInfo.InvariantCulture) });
        var run = new Run(runProps, new Text(text ?? "") { Space = SpaceProcessingModeValues.Preserve });
        return new Paragraph(run);
    }

    /// <summary>A section heading in the house style: bold, underlined, slate.</summary>
    private static Paragraph Heading(string text, int size = 26)
    {
        var runProps = new RunProperties(
            new Bold(),
            new Underline { Val = UnderlineValues.Single },
            new Color { Val = HeadingColor },
            new FontSize { Val = size.ToString(CultureInfo.InvariantCulture) });
        var run = new Run(runProps, new Text(text) { Space = SpaceProcessingModeValues.Preserve });
        return new Paragraph(new ParagraphProperties(new SpacingBetweenLines { Before = "240", After = "60" }), run);
    }

    /// <summary>An Appendix sub-heading: bold slate, smaller, not underlined.</summary>
    private static Paragraph SubHeading(string text)
    {
        var runProps = new RunProperties(new Bold(), new Color { Val = HeadingColor }, new FontSize { Val = "22" });
        var run = new Run(runProps, new Text(text) { Space = SpaceProcessingModeValues.Preserve });
        return new Paragraph(new ParagraphProperties(new SpacingBetweenLines { Before = "160", After = "40" }), run);
    }

    private static Table WordTable(string[] headers, IEnumerable<string[]> rows)
    {
        var table = new Table();
        table.AppendChild(new TableProperties(new TableBorders(
            new TopBorder { Val = BorderValues.Single, Size = 4 },
            new BottomBorder { Val = BorderValues.Single, Size = 4 },
            new LeftBorder { Val = BorderValues.Single, Size = 4 },
            new RightBorder { Val = BorderValues.Single, Size = 4 },
            new InsideHorizontalBorder { Val = BorderValues.Single, Size = 4 },
            new InsideVerticalBorder { Val = BorderValues.Single, Size = 4 })));

        table.AppendChild(WordRow(headers, bold: true));

        var any = false;
        foreach (var r in rows) { table.AppendChild(WordRow(r)); any = true; }
        if (!any)
        {
            var empty = new string[headers.Length];
            empty[0] = "(none)";
            for (var i = 1; i < empty.Length; i++) empty[i] = "";
            table.AppendChild(WordRow(empty));
        }
        return table;
    }

    private static TableRow WordRow(string[] cells, bool bold = false)
    {
        var row = new TableRow();
        foreach (var c in cells)
            row.AppendChild(new TableCell(P(c ?? "", bold: bold, size: 18)));
        return row;
    }

    /// <summary>
    /// Creates the branded header (logo over organisation/team name) and a centred page-number footer,
    /// then references them from the body's section properties. A bad/unsupported logo never fails the
    /// report — the header falls back to text only.
    /// </summary>
    private static void AppendHeaderFooter(MainDocumentPart main, Body body, CaseReportModel m)
    {
        var headerPart = main.AddNewPart<HeaderPart>();
        var header = new Header();

        var org = string.IsNullOrWhiteSpace(m.OrganizationName) ? "[Company Name]" : m.OrganizationName!;
        var team = string.IsNullOrWhiteSpace(m.TeamName) ? "[Team Name]" : m.TeamName!;

        if (m.LogoBytes is { Length: > 0 })
        {
            try { header.AppendChild(LogoParagraph(headerPart, m.LogoBytes, m.LogoContentType)); }
            catch { /* fall through to text-only header */ }
        }
        header.AppendChild(CenteredRun(org, bold: true, size: 24));
        header.AppendChild(CenteredRun(team, bold: false, size: 20));
        headerPart.Header = header;
        var headerId = main.GetIdOfPart(headerPart);

        var footerPart = main.AddNewPart<FooterPart>();
        footerPart.Footer = new Footer(PageNumberParagraph());
        var footerId = main.GetIdOfPart(footerPart);

        body.AppendChild(new SectionProperties(
            new HeaderReference { Type = HeaderFooterValues.Default, Id = headerId },
            new FooterReference { Type = HeaderFooterValues.Default, Id = footerId }));
    }

    private static Paragraph CenteredRun(string text, bool bold, int size)
    {
        var runProps = new RunProperties();
        if (bold) runProps.Append(new Bold());
        runProps.Append(new FontSize { Val = size.ToString(CultureInfo.InvariantCulture) });
        return new Paragraph(
            new ParagraphProperties(new Justification { Val = JustificationValues.Center }),
            new Run(runProps, new Text(text) { Space = SpaceProcessingModeValues.Preserve }));
    }

    private static Paragraph PageNumberParagraph() => new(
        new ParagraphProperties(new Justification { Val = JustificationValues.Center }),
        new Run(new FieldChar { FieldCharType = FieldCharValues.Begin }),
        new Run(new FieldCode(" PAGE ") { Space = SpaceProcessingModeValues.Preserve }),
        new Run(new FieldChar { FieldCharType = FieldCharValues.End }));

    private static Paragraph LogoParagraph(HeaderPart headerPart, byte[] bytes, string? contentType)
    {
        var isPng = (contentType ?? "").Contains("png", StringComparison.OrdinalIgnoreCase);
        var imagePart = headerPart.AddImagePart(isPng ? ImagePartType.Png : ImagePartType.Jpeg);
        using (var stream = new MemoryStream(bytes)) imagePart.FeedData(stream);
        var relId = headerPart.GetIdOfPart(imagePart);

        // Fit the logo into a small header box, preserving aspect ratio (assume 96 DPI: 1px = 9525 EMU).
        int wPx = 160, hPx = 48;
        if (TryGetImageSize(bytes, out var iw, out var ih) && iw > 0 && ih > 0)
        {
            const int maxH = 48, maxW = 320;
            var scale = Math.Min((double)maxH / ih, (double)maxW / iw);
            wPx = Math.Max(1, (int)Math.Round(iw * scale));
            hPx = Math.Max(1, (int)Math.Round(ih * scale));
        }
        long cx = wPx * 9525L, cy = hPx * 9525L;

        var drawing = new Drawing(
            new DW.Inline(
                new DW.Extent { Cx = cx, Cy = cy },
                new DW.EffectExtent { LeftEdge = 0, TopEdge = 0, RightEdge = 0, BottomEdge = 0 },
                new DW.DocProperties { Id = 1U, Name = "Logo" },
                new DW.NonVisualGraphicFrameDrawingProperties(new A.GraphicFrameLocks { NoChangeAspect = true }),
                new A.Graphic(new A.GraphicData(
                    new PIC.Picture(
                        new PIC.NonVisualPictureProperties(
                            new PIC.NonVisualDrawingProperties { Id = 0U, Name = "logo" },
                            new PIC.NonVisualPictureDrawingProperties()),
                        new PIC.BlipFill(
                            new A.Blip { Embed = relId },
                            new A.Stretch(new A.FillRectangle())),
                        new PIC.ShapeProperties(
                            new A.Transform2D(
                                new A.Offset { X = 0L, Y = 0L },
                                new A.Extents { Cx = cx, Cy = cy }),
                            new A.PresetGeometry(new A.AdjustValueList()) { Preset = A.ShapeTypeValues.Rectangle }))
                )
                { Uri = "http://schemas.openxmlformats.org/drawingml/2006/picture" }))
            {
                DistanceFromTop = 0U,
                DistanceFromBottom = 0U,
                DistanceFromLeft = 0U,
                DistanceFromRight = 0U
            });

        return new Paragraph(
            new ParagraphProperties(new Justification { Val = JustificationValues.Center }),
            new Run(drawing));
    }

    /// <summary>Reads intrinsic pixel dimensions from a PNG or JPEG byte stream (no image library needed).</summary>
    private static bool TryGetImageSize(byte[] b, out int width, out int height)
    {
        width = height = 0;
        // PNG: 8-byte signature, then IHDR chunk with big-endian width/height at offsets 16 and 20.
        if (b.Length >= 24 && b[0] == 0x89 && b[1] == 0x50 && b[2] == 0x4E && b[3] == 0x47)
        {
            width = (b[16] << 24) | (b[17] << 16) | (b[18] << 8) | b[19];
            height = (b[20] << 24) | (b[21] << 16) | (b[22] << 8) | b[23];
            return true;
        }
        // JPEG: scan segments for a Start-Of-Frame marker carrying height/width.
        if (b.Length >= 4 && b[0] == 0xFF && b[1] == 0xD8)
        {
            var i = 2;
            while (i + 9 < b.Length)
            {
                if (b[i] != 0xFF) { i++; continue; }
                var marker = b[i + 1];
                if (marker is >= 0xC0 and <= 0xCF && marker != 0xC4 && marker != 0xC8 && marker != 0xCC)
                {
                    height = (b[i + 5] << 8) | b[i + 6];
                    width = (b[i + 7] << 8) | b[i + 8];
                    return true;
                }
                var len = (b[i + 2] << 8) | b[i + 3];
                if (len <= 0) break;
                i += 2 + len;
            }
        }
        return false;
    }
}
