using System.Globalization;
using IncidentManager.Domain.Enums;
using System.IO.Compression;
using System.Text;
using IncidentManager.Domain.Entities;

namespace IncidentManager.Application.Compliance;

/// <summary>
/// Renders a <see cref="ComplianceBundleModel"/> into the files of the evidence bundle and zips them.
/// Everything here is deterministic and self-describing so an examiner can independently re-verify the
/// package (see <c>VERIFY.txt</c>) without this application.
/// </summary>
public static class ComplianceBundlePack
{
    private const string Nl = "\r\n";

    /// <summary>Builds the zip archive bytes: manifest, audit-chain CSV, seals CSV, public key, verify guide.</summary>
    public static byte[] Zip(ComplianceBundleModel m)
    {
        using var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
        {
            AddEntry(zip, "manifest.txt", Manifest(m));
            AddEntry(zip, "audit-chain.csv", AuditChainCsv(m.Segment));
            AddEntry(zip, "seals.csv", SealsCsv(m.Seals));
            AddEntry(zip, "signing-public-key.pem", m.PublicKeyPem);
            foreach (var k in m.RetiredKeys ?? [])
                AddEntry(zip, $"retired-public-keys/{k.KeyId}.pem", k.PublicKeyPem);
            AddEntry(zip, "VERIFY.txt", VerifyReadme());
        }
        return ms.ToArray();
    }

    private static void AddEntry(ZipArchive zip, string name, string content)
    {
        var entry = zip.CreateEntry(name, CompressionLevel.Optimal);
        using var stream = entry.Open();
        var bytes = Encoding.UTF8.GetBytes(content);
        stream.Write(bytes, 0, bytes.Length);
    }

    public static string Manifest(ComplianceBundleModel m)
    {
        var sb = new StringBuilder();
        void Line(string s = "") => sb.Append(s).Append(Nl);

        Line("CASEBOOK COMPLIANCE EVIDENCE BUNDLE");
        Line("===================================");
        Line("A tamper-evident extract of the audit record for regulatory and examination use");
        Line("(supports NYDFS 23 NYCRR Part 500 §500.17(b) certification and DFS examination requests).");
        Line();
        Line($"Generated (UTC) : {Utc(m.GeneratedAtUtc)}");
        Line($"Generated by    : {m.GeneratedByDisplay} ({m.GeneratedByUserId})");
        Line($"Coverage (UTC)  : {Utc(m.FromUtc)}  through  {Utc(m.ToUtc)}");
        Line();
        Line("AUDIT CHAIN SEGMENT");
        Line("-------------------");
        Line($"Entries in range   : {m.Segment.Count}");
        Line(m.SegmentFirstSequence is { } f && m.SegmentLastSequence is { } l
            ? $"Sequence span      : #{f} through #{l}"
            : "Sequence span      : (no entries in this range)");
        Line($"Total chain length : {m.TotalChainLength} entries (all time)");
        Line();
        Line("CHAIN INTEGRITY");
        Line("---------------");
        if (m.ChainResult.IsValid)
        {
            Line("Whole-chain verification : VALID. No altered, inserted, or deleted entries.");
            Line($"Chain head               : #{m.ChainHeadSequence}");
            Line($"Chain head hash          : {m.ChainHeadHash}");
        }
        else
        {
            Line($"Whole-chain verification : BROKEN at sequence #{m.ChainResult.FirstBrokenSequence}");
            Line($"Detail                   : {m.ChainResult.Detail}");
        }
        Line();
        Line("INTEGRITY SEALS");
        Line("---------------");
        Line($"Signing algorithm : {m.Algorithm}");
        Line($"Signing key id    : {m.KeyId}");
        Line(m.CoveringSeal is { } cov
            ? $"Covering seal     : #{cov.Seal.UpToSequence} sealed {Utc(cov.Seal.SealedAtUtc)}, {SealVerdict(cov)}"
            : "Covering seal     : NONE. The end of this range is not yet under an integrity seal.");
        if (m.CoveringSeal is not null)
            Line("                    (the earliest seal that covers the last entry in this range)");
        Line($"Seals listed      : {m.Seals.Count}");
        foreach (var s in m.Seals)
            Line($"   #{s.Seal.UpToSequence} sealed {Utc(s.Seal.SealedAtUtc)} key {s.Seal.KeyId}, {SealVerdict(s)}");
        Line();
        Line("CONTENTS");
        Line("--------");
        Line("manifest.txt            This summary.");
        Line("audit-chain.csv         Every audit entry in range, with per-entry and previous hashes.");
        Line("seals.csv               The signed seals covering this range, with verification results.");
        Line("signing-public-key.pem  Public key to independently verify the seal signatures.");
        if (m.RetiredKeys is { Count: > 0 } retired)
            Line($"retired-public-keys/    Earlier signing keys ({string.Join(", ", retired.Select(k => k.KeyId))}), for seals they signed.");
        Line("VERIFY.txt              How to independently verify this bundle.");
        Line();
        Line("Generated by CaseBook. This export is itself recorded in the audit trail.");
        return sb.ToString();
    }

    public static string AuditChainCsv(IReadOnlyList<AuditLogEntry> entries)
    {
        var sb = new StringBuilder();
        sb.Append("Sequence,AtUtc,Actor,Action,EntityType,EntityId,CaseNumber,Summary,BeforeJson,AfterJson,PrevHash,EntryHash,Reason,EntityLabel").Append(Nl);
        foreach (var e in entries)
        {
            Field(sb, e.Sequence.ToString(CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, e.AtUtc.ToString("o", CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, e.Actor); Comma(sb);
            Field(sb, e.Action.ToString()); Comma(sb);
            Field(sb, e.EntityType); Comma(sb);
            Field(sb, e.EntityId ?? ""); Comma(sb);
            Field(sb, e.CaseNumber ?? ""); Comma(sb);
            Field(sb, e.Summary ?? ""); Comma(sb);
            Field(sb, e.BeforeJson ?? ""); Comma(sb);
            Field(sb, e.AfterJson ?? ""); Comma(sb);
            Field(sb, e.PrevHash); Comma(sb);
            Field(sb, e.EntryHash); Comma(sb);
            // Reason and EntityLabel are in the hash only when present; a row with neither leaves both blank.
            Field(sb, e.Reason ?? ""); Comma(sb);
            Field(sb, e.EntityLabel ?? "");
            sb.Append(Nl);
        }
        return sb.ToString();
    }

    public static string SealsCsv(IReadOnlyList<SealLine> seals)
    {
        var sb = new StringBuilder();
        sb.Append("UpToSequence,SealedAtUtc,SealedBy,Algorithm,KeyId,ChainHeadHash,SignatureValid,ChainMatches,Signature").Append(Nl);
        foreach (var s in seals)
        {
            var seal = s.Seal;
            Field(sb, seal.UpToSequence.ToString(CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, seal.SealedAtUtc.ToString("o", CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, seal.SealedBy); Comma(sb);
            Field(sb, seal.Algorithm); Comma(sb);
            Field(sb, seal.KeyId); Comma(sb);
            Field(sb, seal.ChainHeadHash); Comma(sb);
            Field(sb, s.SignatureValid ? "true" : "false"); Comma(sb);
            Field(sb, s.ChainMatches ? "true" : "false"); Comma(sb);
            Field(sb, seal.Signature);
            sb.Append(Nl);
        }
        return sb.ToString();
    }

    public static string VerifyReadme()
    {
        var sb = new StringBuilder();
        void Line(string s = "") => sb.Append(s).Append(Nl);

        Line("INDEPENDENTLY VERIFYING THIS BUNDLE");
        Line("===================================");
        Line("This package can be verified without CaseBook. Two independent checks together");
        Line("establish that the record is intact and was sealed by our key.");
        Line();
        Line("1) AUDIT CHAIN  (audit-chain.csv)");
        Line("   Each row is one append-only entry. Its EntryHash is:");
        Line();
        Line("       EntryHash = SHA-256( canonical + \"|\" + PrevHash )   (lowercase hex)");
        Line();
        Line("   where canonical is the '|'-joined fields, in this exact order:");
        Line("       Sequence, AtUtc, Actor, Action, EntityType, EntityId,");
        Line("       CaseNumber, Summary, BeforeJson, AfterJson");
        Line("   - AtUtc is the ISO-8601 round-trip form ('o').");
        Line("   - Action is the integer value of the action:");
        foreach (var chunk in Enum.GetValues<AuditAction>().Select(a => $"{a}={(int)a}").Chunk(4))
            Line("       " + string.Join(", ", chunk));
        Line("   - An empty/absent field contributes an empty string.");
        Line("   - Then, only when the row has one, '|' + Reason; then, only when it has one,");
        Line("     '|' + EntityLabel (blank in the CSV means absent: nothing is appended).");
        Line("   Recompute each row's hash and confirm it equals EntryHash, and that each row's");
        Line("   PrevHash equals the previous row's EntryHash (the first row in the full chain links");
        Line("   against an empty previous hash).");
        Line();
        Line("2) INTEGRITY SEALS  (seals.csv + signing-public-key.pem)");
        Line("   Check each seal with the public key its KeyId names: signing-public-key.pem for the");
        Line("   current key (the manifest gives its id), or retired-public-keys/<KeyId>.pem for a seal");
        Line("   signed before the key was changed. In the commands below, use that file in place of");
        Line("   signing-public-key.pem.");
        Line();
        Line("   Each seal is an RSASSA-PSS signature over the '|'-joined payload:");
        Line();
        Line("       UpToSequence, ChainHeadHash, SealedAtUtc, SealedBy");
        Line();
        Line("   (SealedAtUtc in ISO-8601 'o' form, copied exactly as it appears in seals.csv).");
        Line("   Signature parameters: RSASSA-PSS, SHA-256, MGF1 with SHA-256, salt length 32 bytes.");
        Line("   The salt length must be set explicitly: a verifier left at a different salt length");
        Line("   reports a genuine seal as invalid. With OpenSSL 1.1.1 or later (bash), per seal:");
        Line();
        Line("       printf '%s' '<UpToSequence>|<ChainHeadHash>|<SealedAtUtc>|<SealedBy>' > payload.txt");
        Line("       printf '%s' '<Signature>' | openssl base64 -d -A > seal.sig");
        Line("       openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:32 \\");
        Line("           -sigopt rsa_mgf1_md:sha256 -verify signing-public-key.pem -signature seal.sig payload.txt");
        Line();
        Line("   A seal whose Algorithm is RSASSA-PKCS1-v1_5-SHA256 was made before v1.4.0; verify it the");
        Line("   same way without the three -sigopt options (OpenSSL's default padding is PKCS#1 v1.5).");
        Line();
        Line("   OpenSSL prints \"Verified OK\" for an authentic seal. Then confirm ChainHeadHash equals");
        Line("   the EntryHash of the audit entry at UpToSequence. A valid signature plus a matching head");
        Line("   proves the history up to that point is unchanged since it was sealed.");
        Line();
        Line("   If the organization streams CaseBook's security events to a SIEM, each seal was also");
        Line("   sent there as event 5004 when it was made (targetId = UpToSequence, detail carries");
        Line("   head=<ChainHeadHash> and key=<KeyId>). Ask for those events and confirm each seal here has");
        Line("   one with the same hash and key: the SIEM is run apart from CaseBook, so a seal added,");
        Line("   altered or re-signed later would be missing there or differ.");
        Line();
        Line("The SignatureValid / ChainMatches columns in seals.csv record the result of the same two");
        Line("checks performed by CaseBook at the moment this bundle was generated.");
        return sb.ToString();
    }

    private static string SealVerdict(SealLine s) => (s.SignatureValid, s.ChainMatches) switch
    {
        (true, true) => "signature AUTHENTIC, history UNCHANGED",
        (false, _) => "signature INVALID (altered or signed by a different key)",
        (true, false) => "signature authentic but history CHANGED since sealing",
    };

    private static string Utc(DateTimeOffset t) =>
        t.UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);

    private static void Comma(StringBuilder sb) => sb.Append(',');

    /// <summary>RFC-4180 escaping: quote when the field contains a comma, quote, CR or LF; double embedded quotes.</summary>
    private static void Field(StringBuilder sb, string value)
    {
        if (value.IndexOfAny(['"', ',', '\r', '\n']) < 0) { sb.Append(value); return; }
        sb.Append('"').Append(value.Replace("\"", "\"\"")).Append('"');
    }
}
