using System.Globalization;
using System.IO.Compression;
using System.Text;
using IncidentManager.Domain.Entities;

namespace IncidentManager.Application.Compliance;

/// <summary>
/// Renders a <see cref="ComplianceBundleModel"/> into the files of the evidence bundle and zips them.
/// Everything here is deterministic and self-describing so an examiner can independently re-verify the
/// package (see <c>VERIFY.txt</c>) without this application.
/// </summary>
public static class ComplianceBundlePack
{
    private const string Nl = "\r\n";

    /// <summary>Builds the zip archive bytes: manifest, audit-chain CSV, seals CSV, public key, verify guide.</summary>
    public static byte[] Zip(ComplianceBundleModel m)
    {
        using var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
        {
            AddEntry(zip, "manifest.txt", Manifest(m));
            AddEntry(zip, "audit-chain.csv", AuditChainCsv(m.Segment));
            AddEntry(zip, "seals.csv", SealsCsv(m.Seals));
            AddEntry(zip, "signing-public-key.pem", m.PublicKeyPem);
            AddEntry(zip, "VERIFY.txt", VerifyReadme());
        }
        return ms.ToArray();
    }

    private static void AddEntry(ZipArchive zip, string name, string content)
    {
        var entry = zip.CreateEntry(name, CompressionLevel.Optimal);
        using var stream = entry.Open();
        var bytes = Encoding.UTF8.GetBytes(content);
        stream.Write(bytes, 0, bytes.Length);
    }

    public static string Manifest(ComplianceBundleModel m)
    {
        var sb = new StringBuilder();
        void Line(string s = "") => sb.Append(s).Append(Nl);

        Line("INCIDENT MANAGER — COMPLIANCE EVIDENCE BUNDLE");
        Line("=============================================");
        Line("A tamper-evident extract of the audit record for regulatory / examination use");
        Line("(supports NYDFS 23 NYCRR Part 500 §500.17(b) certification and DFS examination requests).");
        Line();
        Line($"Generated (UTC) : {Utc(m.GeneratedAtUtc)}");
        Line($"Generated by    : {m.GeneratedByDisplay} ({m.GeneratedByUserId})");
        Line($"Coverage (UTC)  : {Utc(m.FromUtc)}  through  {Utc(m.ToUtc)}");
        Line();
        Line("AUDIT CHAIN SEGMENT");
        Line("-------------------");
        Line($"Entries in range   : {m.Segment.Count}");
        Line(m.SegmentFirstSequence is { } f && m.SegmentLastSequence is { } l
            ? $"Sequence span      : #{f} through #{l}"
            : "Sequence span      : (no entries in this range)");
        Line($"Total chain length : {m.TotalChainLength} entries (all time)");
        Line();
        Line("CHAIN INTEGRITY");
        Line("---------------");
        if (m.ChainResult.IsValid)
        {
            Line("Whole-chain verification : VALID — no altered, inserted, or deleted entries.");
            Line($"Chain head               : #{m.ChainHeadSequence}");
            Line($"Chain head hash          : {m.ChainHeadHash}");
        }
        else
        {
            Line($"Whole-chain verification : BROKEN at sequence #{m.ChainResult.FirstBrokenSequence}");
            Line($"Detail                   : {m.ChainResult.Detail}");
        }
        Line();
        Line("INTEGRITY SEALS");
        Line("---------------");
        Line($"Signing algorithm : {m.Algorithm}");
        Line($"Signing key id    : {m.KeyId}");
        Line(m.CoveringSeal is { } cov
            ? $"Covering seal     : #{cov.Seal.UpToSequence} sealed {Utc(cov.Seal.SealedAtUtc)} — {SealVerdict(cov)}"
            : "Covering seal     : NONE — the end of this range is not yet under an integrity seal.");
        if (m.CoveringSeal is not null)
            Line("                    (the earliest seal that covers the last entry in this range)");
        Line($"Seals listed      : {m.Seals.Count}");
        foreach (var s in m.Seals)
            Line($"   #{s.Seal.UpToSequence} sealed {Utc(s.Seal.SealedAtUtc)} key {s.Seal.KeyId} — {SealVerdict(s)}");
        Line();
        Line("CONTENTS");
        Line("--------");
        Line("manifest.txt            This summary.");
        Line("audit-chain.csv         Every audit entry in range, with per-entry and previous hashes.");
        Line("seals.csv               The signed seals covering this range, with verification results.");
        Line("signing-public-key.pem  Public key to independently verify the seal signatures.");
        Line("VERIFY.txt              How to independently verify this bundle.");
        Line();
        Line("Generated by CaseBook. This export is itself recorded in the audit trail.");
        return sb.ToString();
    }

    public static string AuditChainCsv(IReadOnlyList<AuditLogEntry> entries)
    {
        var sb = new StringBuilder();
        sb.Append("Sequence,AtUtc,Actor,Action,EntityType,EntityId,CaseNumber,Summary,BeforeJson,AfterJson,PrevHash,EntryHash").Append(Nl);
        foreach (var e in entries)
        {
            Field(sb, e.Sequence.ToString(CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, e.AtUtc.ToString("o", CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, e.Actor); Comma(sb);
            Field(sb, e.Action.ToString()); Comma(sb);
            Field(sb, e.EntityType); Comma(sb);
            Field(sb, e.EntityId ?? ""); Comma(sb);
            Field(sb, e.CaseNumber ?? ""); Comma(sb);
            Field(sb, e.Summary ?? ""); Comma(sb);
            Field(sb, e.BeforeJson ?? ""); Comma(sb);
            Field(sb, e.AfterJson ?? ""); Comma(sb);
            Field(sb, e.PrevHash); Comma(sb);
            Field(sb, e.EntryHash);
            sb.Append(Nl);
        }
        return sb.ToString();
    }

    public static string SealsCsv(IReadOnlyList<SealLine> seals)
    {
        var sb = new StringBuilder();
        sb.Append("UpToSequence,SealedAtUtc,SealedBy,Algorithm,KeyId,ChainHeadHash,SignatureValid,ChainMatches,Signature").Append(Nl);
        foreach (var s in seals)
        {
            var seal = s.Seal;
            Field(sb, seal.UpToSequence.ToString(CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, seal.SealedAtUtc.ToString("o", CultureInfo.InvariantCulture)); Comma(sb);
            Field(sb, seal.SealedBy); Comma(sb);
            Field(sb, seal.Algorithm); Comma(sb);
            Field(sb, seal.KeyId); Comma(sb);
            Field(sb, seal.ChainHeadHash); Comma(sb);
            Field(sb, s.SignatureValid ? "true" : "false"); Comma(sb);
            Field(sb, s.ChainMatches ? "true" : "false"); Comma(sb);
            Field(sb, seal.Signature);
            sb.Append(Nl);
        }
        return sb.ToString();
    }

    public static string VerifyReadme()
    {
        var sb = new StringBuilder();
        void Line(string s = "") => sb.Append(s).Append(Nl);

        Line("INDEPENDENTLY VERIFYING THIS BUNDLE");
        Line("===================================");
        Line("This package can be verified without the IncidentManager application. Two independent");
        Line("checks together establish that the record is intact and was sealed by our key.");
        Line();
        Line("1) AUDIT CHAIN  (audit-chain.csv)");
        Line("   Each row is one append-only entry. Its EntryHash is:");
        Line();
        Line("       EntryHash = SHA-256( canonical + \"|\" + PrevHash )   (lowercase hex)");
        Line();
        Line("   where canonical is the '|'-joined fields, in this exact order:");
        Line("       Sequence, AtUtc, Actor, Action, EntityType, EntityId,");
        Line("       CaseNumber, Summary, BeforeJson, AfterJson");
        Line("   - AtUtc is the ISO-8601 round-trip form ('o').");
        Line("   - Action is the integer value of the action (Create=0, Update=1, SoftDelete=2,");
        Line("     Access=3, Login=4, Logout=5, ClassificationChanged=6, StatusChanged=7,");
        Line("     EvidenceUploaded=8, EvidenceDownloaded=9, ReportGenerated=10, ReportFinalized=11,");
        Line("     LegalReferral=12, IntegritySeal=13, IntegrityVerification=14, Export=15).");
        Line("   - An empty/absent field contributes an empty string.");
        Line("   Recompute each row's hash and confirm it equals EntryHash, and that each row's");
        Line("   PrevHash equals the previous row's EntryHash (the first row in the full chain links");
        Line("   against an empty previous hash).");
        Line();
        Line("2) INTEGRITY SEALS  (seals.csv + signing-public-key.pem)");
        Line("   Each seal is an RSASSA-PKCS1-v1_5 (SHA-256) signature over the '|'-joined payload:");
        Line();
        Line("       UpToSequence, ChainHeadHash, SealedAtUtc, SealedBy");
        Line();
        Line("   (SealedAtUtc in ISO-8601 'o' form). Verify the base64 Signature against that payload");
        Line("   using signing-public-key.pem, and confirm ChainHeadHash equals the EntryHash of the");
        Line("   audit entry at UpToSequence. A valid signature plus a matching head proves the history");
        Line("   up to that point is unchanged since it was sealed.");
        Line();
        Line("The SignatureValid / ChainMatches columns in seals.csv record the result of the same two");
        Line("checks performed by IncidentManager at the moment this bundle was generated.");
        return sb.ToString();
    }

    private static string SealVerdict(SealLine s) => (s.SignatureValid, s.ChainMatches) switch
    {
        (true, true) => "signature AUTHENTIC, history UNCHANGED",
        (false, _) => "signature INVALID (altered or signed by a different key)",
        (true, false) => "signature authentic but history CHANGED since sealing",
    };

    private static string Utc(DateTimeOffset t) =>
        t.UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);

    private static void Comma(StringBuilder sb) => sb.Append(',');

    /// <summary>RFC-4180 escaping: quote when the field contains a comma, quote, CR or LF; double embedded quotes.</summary>
    private static void Field(StringBuilder sb, string value)
    {
        if (value.IndexOfAny(['"', ',', '\r', '\n']) < 0) { sb.Append(value); return; }
        sb.Append('"').Append(value.Replace("\"", "\"\"")).Append('"');
    }
}
