#Requires -Version 5.1
<#
.SYNOPSIS
    Provisions the CaseBook SQL Server 2022 database and the app-pool login (Windows auth).

.DESCRIPTION
    Wraps deploy/sql/01-Create-Database.sql. Creates the database (FULL recovery,
    RCSI on) and a least-privilege login/user for the IIS application-pool identity.
    Integrated authentication only - no SQL credentials are created or stored.

    Run on (or with line-of-sight to) the SQL Server, as an account that is sysadmin
    on the target instance. Idempotent - safe to re-run.

    Values can come from an answers file (-ConfigFile casebook.config.psd1, generated by
    New-CaseBookConfig.ps1) OR as parameters. A parameter you pass explicitly overrides
    the file.

.PARAMETER ConfigFile
    Path to a casebook.config.psd1 answers file (see casebook.config.template.psd1). Fills
    any parameter you don't pass explicitly. Optional - you can pass everything as parameters.

.PARAMETER SqlInstance
    Target instance, e.g. "SQLHOST" or "SQLHOST\INSTANCE". Required (parameter or config file).

.PARAMETER AppAccount
    Windows account the CaseBook IIS app pool runs as. For a gMSA include the
    trailing '$', e.g. "CONTOSO\svc-casebook$". Must already exist in AD.

.PARAMETER DbName
    Database name. Default: CaseBook.

.PARAMETER DataPath / LogPath
    Optional explicit folders for the data/log files. Omit to use instance defaults.

.PARAMETER SchemaMode
    AppMigrates (default) - grant db_owner; the app applies EF migrations at startup.
    DbaApplies             - grant datareader/datawriter/EXECUTE only; a DBA applies
                             the schema. Combine with -ApplySchema to run it now.

.PARAMETER ApplySchema
    When SchemaMode=DbaApplies, also execute deploy/sql/casebook-schema-sqlserver.sql
    against the database (as the sysadmin running this script).

.EXAMPLE
    .\Install-Database.ps1 -ConfigFile .\casebook.config.psd1

.EXAMPLE
    .\Install-Database.ps1 -SqlInstance SQLHOST\PROD -AppAccount "CONTOSO\svc-casebook$"
#>
[CmdletBinding()]
param(
    [string] $ConfigFile,
    [string] $SqlInstance,
    [string] $AppAccount,
    [string] $DbName,
    [string] $DataPath,
    [string] $LogPath,
    [ValidateSet('AppMigrates','DbaApplies')] [string] $SchemaMode,
    [switch] $ApplySchema
)

$ErrorActionPreference = 'Stop'

# --- Merge an optional answers file (explicit -Params win) --------------------
if ($ConfigFile) {
    if (-not (Test-Path $ConfigFile)) { throw "Config file not found: $ConfigFile" }
    $cfg = Import-PowerShellDataFile -Path $ConfigFile
    foreach ($name in 'SqlInstance','AppAccount','DbName','DataPath','LogPath','SchemaMode') {
        if (-not $PSBoundParameters.ContainsKey($name) -and $cfg.ContainsKey($name) -and "$($cfg[$name])" -ne '') {
            Set-Variable -Name $name -Value $cfg[$name]
        }
    }
}
# Defaults for anything still unset (built-in default is the lowest precedence).
if (-not $DbName)        { $DbName = 'CaseBook' }
if ($null -eq $DataPath) { $DataPath = '' }
if ($null -eq $LogPath)  { $LogPath  = '' }
if (-not $SchemaMode)    { $SchemaMode = 'AppMigrates' }
# Required, whichever source they came from.
$missing = @()
if (-not $SqlInstance) { $missing += 'SqlInstance' }
if (-not $AppAccount)  { $missing += 'AppAccount' }
if ($missing.Count) {
    throw "Missing required value(s): $($missing -join ', '). Pass as a -Parameter or set them in -ConfigFile (see casebook.config.template.psd1)."
}
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$createSql = Join-Path $scriptDir 'sql\01-Create-Database.sql'
$schemaSql = Join-Path $scriptDir 'sql\casebook-schema-sqlserver.sql'

if (-not (Test-Path $createSql)) { throw "Missing $createSql" }

# Pick an execution engine: prefer the SqlServer module's Invoke-Sqlcmd, fall back to sqlcmd.exe.
$useModule = $false
if (Get-Command Invoke-Sqlcmd -ErrorAction SilentlyContinue) {
    $useModule = $true
} elseif (-not (Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)) {
    throw "Neither the SqlServer PowerShell module (Invoke-Sqlcmd) nor sqlcmd.exe is available. " +
          "Install with:  Install-Module SqlServer -Scope CurrentUser"
}

function Invoke-Sql {
    param([string] $InputFile, [hashtable] $Vars, [switch] $NoDbVars)
    if ($useModule) {
        $varArray = $Vars.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }
        Invoke-Sqlcmd -ServerInstance $SqlInstance -InputFile $InputFile -Variable $varArray `
                      -TrustServerCertificate -QueryTimeout 0 -OutputSqlErrors $true -Verbose
    } else {
        $varArgs = @()
        foreach ($k in $Vars.Keys) { $varArgs += @('-v', ("{0}={1}" -f $k, $Vars[$k])) }
        & sqlcmd.exe -S $SqlInstance -E -b -C -i $InputFile @varArgs
        if ($LASTEXITCODE -ne 0) { throw "sqlcmd failed (exit $LASTEXITCODE) on $InputFile" }
    }
}

Write-Host "==> Provisioning database [$DbName] on [$SqlInstance] for [$AppAccount] (mode: $SchemaMode)" -ForegroundColor Cyan

$vars = @{
    DbName     = $DbName
    AppAccount = $AppAccount
    DataPath   = $DataPath
    LogPath    = $LogPath
    SchemaMode = $SchemaMode
}
Invoke-Sql -InputFile $createSql -Vars $vars

if ($SchemaMode -eq 'DbaApplies' -and $ApplySchema) {
    if (-not (Test-Path $schemaSql)) { throw "Missing $schemaSql (regenerate via deploy/README)" }
    Write-Host "==> Applying schema from $([System.IO.Path]::GetFileName($schemaSql))" -ForegroundColor Cyan
    if ($useModule) {
        Invoke-Sqlcmd -ServerInstance $SqlInstance -Database $DbName -InputFile $schemaSql `
                      -TrustServerCertificate -QueryTimeout 0 -OutputSqlErrors $true
    } else {
        & sqlcmd.exe -S $SqlInstance -E -b -C -d $DbName -i $schemaSql
        if ($LASTEXITCODE -ne 0) { throw "sqlcmd failed applying schema (exit $LASTEXITCODE)" }
    }
}

Write-Host "==> Database provisioning complete." -ForegroundColor Green
if ($SchemaMode -eq 'AppMigrates') {
    Write-Host "    The schema is created automatically on the app's first start (EF migrations)." -ForegroundColor Gray
}
