#Requires -Version 5.1
#Requires -RunAsAdministrator
<#
.SYNOPSIS
    First-install of the CaseBook web app on a Windows Server 2022 IIS host.

.DESCRIPTION
    End-to-end app install (run AFTER Install-Database.ps1):
      1. Publishes the Blazor Server app (dotnet publish -c Release) to the site folder.
      2. Creates the ACL-restricted data root (evidence / reports / keys / seals / ops)
         OUTSIDE the web root.
      3. Writes appsettings.Production.json from the template with your values.
      4. Creates/updates the IIS application pool (No Managed Code, your service identity)
         and website, enabling Windows Authentication and disabling Anonymous.
      5. Grants the app-pool identity least-privilege NTFS rights.

    Integrated auth throughout - no secrets are written by this script. Provide the app-pool
    identity as a gMSA (recommended, passwordless) or a domain service account.
    Idempotent - safe to re-run to update the app.

    Values can come from an answers file (-ConfigFile casebook.config.psd1, generated by
    New-CaseBookConfig.ps1 - the same file Install-Database.ps1 uses) OR as parameters. A
    parameter you pass explicitly overrides the file. A non-gMSA password is NEVER read from
    the file - pass -AppPoolCredential and you'll be prompted securely.

.PARAMETER ConfigFile
    Path to a casebook.config.psd1 answers file (see casebook.config.template.psd1). Fills any
    parameter you don't pass explicitly. Optional - you can pass everything as parameters.

.PARAMETER AppPoolIdentity
    Service account the app runs as, matching the SQL login from Install-Database.ps1.
    (Config-file key / alias: AppAccount.) gMSA: "CONTOSO\svc-casebook$" (leave -AppPoolCredential unset).

.PARAMETER AppPoolCredential
    Only for a NON-gMSA domain service account: a PSCredential (you are prompted securely).
    Omit for a gMSA.

.PARAMETER SitePath
    Web root the app is published to, e.g. "D:\inetpub\casebook". Kept separate from DataRoot.

.PARAMETER DataRoot
    Root for evidence/reports/keys/seals/ops, OUTSIDE the web root, e.g. "E:\CaseBookData".

.PARAMETER Hostname
    Public host header, e.g. "casebook.contoso.com".

.PARAMETER SqlInstance / DbName
    SQL Server instance and database from Install-Database.ps1.

.PARAMETER CertificateThumbprint
    Thumbprint of an installed TLS cert for an HTTPS (443) binding. If omitted, an HTTP
    binding is created and you are warned to terminate TLS in front.

.PARAMETER AdGroupAnalysts / Commanders / Leadership / Legal / AppAdmins
    Real AD security-group names mapped to the five application roles.

.PARAMETER SmtpHost / MailDomain
    Optional email settings (email stays disabled until enabled in-app).

.PARAMETER SkipPublish
    Do not run 'dotnet publish' on this host. Use when the server has no nuget.org access
    (NU1100 restore errors) or no SDK: publish on a machine WITH internet, copy the output
    into -SitePath, then run with -SkipPublish to do only IIS + config + ACLs.

.PARAMETER AddNuGetOrgSource
    If no NuGet source is registered (publish would fail NU1100), register nuget.org
    automatically rather than stopping with instructions. Off by default so an intentional
    internal-feed-only policy isn't overridden.

.EXAMPLE
    # Simplest: one answers file for both installers (a gMSA needs no credential).
    .\Install-CaseBook.ps1 -ConfigFile .\casebook.config.psd1
    # Normal (non-gMSA) service account - add the credential prompt:
    .\Install-CaseBook.ps1 -ConfigFile .\casebook.config.psd1 -AppPoolCredential (Get-Credential)

.EXAMPLE
    .\Install-CaseBook.ps1 -AppPoolIdentity "CONTOSO\svc-casebook$" `
        -SitePath D:\inetpub\casebook -DataRoot E:\CaseBookData `
        -Hostname casebook.contoso.com -SqlInstance SQLHOST\PROD -DbName CaseBook `
        -CertificateThumbprint AABBCC... `
        -AdGroupAnalysts SOC-Analysts -AdGroupCommanders SOC-IncidentCommanders `
        -AdGroupLeadership SOC-Leadership -AdGroupLegal Legal-Privacy -AdGroupAppAdmins SOC-AppAdmins
#>
[CmdletBinding()]
param(
    [string] $ConfigFile,

    [Alias('AppAccount')]
    [string] $AppPoolIdentity,
    [System.Management.Automation.PSCredential] $AppPoolCredential,

    [string] $SitePath,
    [string] $DataRoot,
    [string] $Hostname,
    [string] $SqlInstance,
    [string] $DbName = 'CaseBook',

    [string] $SiteName = 'CaseBook',
    [string] $AppPoolName = 'CaseBook',
    [string] $CertificateThumbprint,

    [string] $AdGroupAnalysts,
    [string] $AdGroupCommanders,
    [string] $AdGroupLeadership,
    [string] $AdGroupLegal,
    [string] $AdGroupAppAdmins,

    [string] $SmtpHost = '',
    [string] $MailDomain = '',

    [string] $PublishConfiguration = 'Release',

    # Air-gapped / no nuget.org on this host: publish on a machine WITH internet
    # (dotnet publish src/IncidentManager.Web -c Release -o <folder>), copy the output
    # into -SitePath, then re-run with -SkipPublish to do only IIS + config + ACLs.
    [switch] $SkipPublish,

    # If NO NuGet package source is registered (publish would fail NU1100), register nuget.org
    # automatically instead of stopping. Off by default: a blank source list can be deliberate
    # policy (use an internal feed), and this writes to the running user's NuGet.Config.
    [switch] $AddNuGetOrgSource
)

$ErrorActionPreference = 'Stop'

# --- Merge an optional answers file (explicit -Params win; passwords are never read from it) ---
if ($ConfigFile) {
    if (-not (Test-Path $ConfigFile)) { throw "Config file not found: $ConfigFile" }
    $cfg = Import-PowerShellDataFile -Path $ConfigFile
    # config key -> script variable. 'AppAccount' fills -AppPoolIdentity (one identity for DB + app pool).
    $mapping = [ordered]@{
        AppAccount            = 'AppPoolIdentity'
        SitePath              = 'SitePath'
        DataRoot              = 'DataRoot'
        Hostname              = 'Hostname'
        SqlInstance           = 'SqlInstance'
        DbName                = 'DbName'
        SiteName              = 'SiteName'
        AppPoolName           = 'AppPoolName'
        CertificateThumbprint = 'CertificateThumbprint'
        AdGroupAnalysts       = 'AdGroupAnalysts'
        AdGroupCommanders     = 'AdGroupCommanders'
        AdGroupLeadership     = 'AdGroupLeadership'
        AdGroupLegal          = 'AdGroupLegal'
        AdGroupAppAdmins      = 'AdGroupAppAdmins'
        SmtpHost              = 'SmtpHost'
        MailDomain            = 'MailDomain'
    }
    foreach ($key in $mapping.Keys) {
        $var = $mapping[$key]
        # -AppPoolIdentity may have been bound via its 'AppAccount' alias; treat either as explicit.
        $boundExplicitly = $PSBoundParameters.ContainsKey($var) -or ($var -eq 'AppPoolIdentity' -and $PSBoundParameters.ContainsKey('AppAccount'))
        if (-not $boundExplicitly -and $cfg.ContainsKey($key) -and "$($cfg[$key])" -ne '') {
            Set-Variable -Name $var -Value $cfg[$key]
        }
    }
}
# Required, whichever source they came from.
$required = @{
    AppPoolIdentity = $AppPoolIdentity; SitePath = $SitePath; DataRoot = $DataRoot; Hostname = $Hostname
    SqlInstance = $SqlInstance; AdGroupAnalysts = $AdGroupAnalysts; AdGroupCommanders = $AdGroupCommanders
    AdGroupLeadership = $AdGroupLeadership; AdGroupLegal = $AdGroupLegal; AdGroupAppAdmins = $AdGroupAppAdmins
}
$missing = @($required.GetEnumerator() | Where-Object { [string]::IsNullOrWhiteSpace($_.Value) } | ForEach-Object { $_.Key })
if ($missing.Count) {
    throw "Missing required value(s): $($missing -join ', '). Pass as -Parameters or set them in -ConfigFile (see casebook.config.template.psd1)."
}

$deployDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot  = Split-Path -Parent $deployDir
$webProj   = Join-Path $repoRoot 'src\IncidentManager.Web\IncidentManager.Web.csproj'
$template  = Join-Path $deployDir 'appsettings.Production.template.json'

if (-not (Test-Path $template)) { throw "Missing expected path: $template" }
if (-not $SkipPublish -and -not (Test-Path $webProj)) { throw "Missing expected path: $webProj (use -SkipPublish to install a pre-published app)" }

function Write-Step($m) { Write-Host "==> $m" -ForegroundColor Cyan }

# Preflight: the app-pool identity must resolve to a Windows SID up front - it is used for the NTFS
# ACLs, the IIS app-pool identity, and it must match the SQL login from Install-Database.ps1. Failing
# here (before publish/config) gives a clear message instead of a late IdentityNotMappedException.
try {
    [void] ([System.Security.Principal.NTAccount]::new($AppPoolIdentity)).Translate([System.Security.Principal.SecurityIdentifier])
} catch {
    throw ("The app-pool identity '$AppPoolIdentity' could not be resolved to a Windows account on this host. " +
           "For a group Managed Service Account (gMSA) include the trailing '`$' (e.g. 'AD\svc-casebook`$'). " +
           "For a normal domain account use DOMAIN\sAMAccountName and confirm the account exists and this server " +
           "is domain-joined and can reach a domain controller. It must match the SQL login from Install-Database.ps1.")
}

# Preflight: the ASP.NET Core Module must be registered or IIS can't run the app - it fails with HTTP
# 500.19 (0x8007000d) because the web.config's <aspNetCore> section is unknown. The module ships with the
# .NET Hosting Bundle, NOT the SDK, so a publish-capable box can still be missing it.
$ancm = Join-Path $env:WINDIR 'System32\inetsrv\aspnetcorev2.dll'
if (-not (Test-Path $ancm)) {
    throw ("The ASP.NET Core Module (aspnetcorev2.dll) is not installed, so IIS cannot host the app " +
           "(it would fail with HTTP 500.19). Install the .NET 8 Hosting Bundle from " +
           "https://dotnet.microsoft.com/download/dotnet/8.0 (ASP.NET Core Runtime -> Hosting Bundle), " +
           "run 'iisreset', then re-run this script.")
}

# --- 1. Publish (or use a pre-published folder) -------------------------------
$appDll = Join-Path $SitePath 'IncidentManager.Web.dll'
if ($SkipPublish) {
    Write-Step "Skipping publish; using pre-published app at $SitePath"
    if (-not (Test-Path $appDll)) {
        throw "-SkipPublish was set but $appDll is missing. Publish on a machine with internet " +
              "(dotnet publish $webProj -c $PublishConfiguration -o <folder>) and copy the output into $SitePath first."
    }
} else {
    Write-Step "Publishing CaseBook ($PublishConfiguration) to $SitePath"
    if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
        throw "The .NET 8 SDK ('dotnet') is required on this host to publish. Install the SDK, or publish " +
              "elsewhere, copy the output into $SitePath, and re-run with -SkipPublish."
    }

    # Preflight: no registered/enabled NuGet source => restore fails NU1100 for every package. Catch it
    # here with an exact fix instead of a slow, opaque publish failure.
    $sourcesOut = (& dotnet nuget list source 2>&1 | Out-String)
    if ($sourcesOut -notmatch '\[Enabled\]') {
        $addCmd = 'dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org'
        if ($AddNuGetOrgSource) {
            Write-Step "No enabled NuGet source found; registering nuget.org"
            & dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
            if ($LASTEXITCODE -ne 0) { throw "Failed to add the nuget.org source (exit $LASTEXITCODE)." }
        } else {
            throw ("No enabled NuGet package source is registered for this user, so 'dotnet publish' will fail " +
                   "with NU1100. Register nuget.org:  $addCmd  (or re-run with -AddNuGetOrgSource), point at your " +
                   "internal feed, or publish elsewhere and re-run with -SkipPublish. Note: NuGet sources are " +
                   "per-user, so register them as the same account that runs this script.")
        }
    }

    New-Item -ItemType Directory -Force -Path $SitePath | Out-Null
    & dotnet publish $webProj -c $PublishConfiguration -o $SitePath --nologo
    if ($LASTEXITCODE -ne 0) {
        throw ("dotnet publish failed (exit $LASTEXITCODE). A NuGet restore error (NU1100) with connectivity " +
               "present usually means no package source is registered: run 'dotnet nuget list source', and if " +
               "nuget.org is missing add it with " +
               "'dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org', then re-run. " +
               "Alternatively publish on another machine and re-run this script with -SkipPublish.")
    }
}

# --- 2. Data root (outside web root) + subfolders -----------------------------
Write-Step "Creating ACL-restricted data root at $DataRoot"
$dataDirs = @('evidence-store','report-output','keys','seals','ops','dp-keys') | ForEach-Object { Join-Path $DataRoot $_ }
foreach ($d in @($DataRoot) + $dataDirs) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

# --- 3. appsettings.Production.json from template -----------------------------
Write-Step "Writing appsettings.Production.json"
$json = Get-Content $template -Raw
$map = @{
    '__PUBLIC_HOSTNAME__'      = $Hostname
    '__SQL_INSTANCE__'         = $SqlInstance
    '__DB_NAME__'              = $DbName
    '__DATA_ROOT__'            = ($DataRoot -replace '\\','\\')   # JSON-escape backslashes
    '__SMTP_HOST__'            = $SmtpHost
    '__MAIL_DOMAIN__'          = $MailDomain
    '__AD_GROUP_ANALYSTS__'    = $AdGroupAnalysts
    '__AD_GROUP_COMMANDERS__'  = $AdGroupCommanders
    '__AD_GROUP_LEADERSHIP__'  = $AdGroupLeadership
    '__AD_GROUP_LEGAL__'       = $AdGroupLegal
    '__AD_GROUP_APPADMINS__'   = $AdGroupAppAdmins
}
foreach ($k in $map.Keys) { $json = $json.Replace($k, $map[$k]) }
# Guard against a genuinely-unsubstituted value: check only the known placeholder keys, so descriptive
# text in the template (which may itself mention the token format) can never false-positive.
$leftover = @($map.Keys | Where-Object { $json.Contains($_) })
if ($leftover.Count) { throw "Unsubstituted placeholder(s) remain in the config: $($leftover -join ', ')" }
$prodSettings = Join-Path $SitePath 'appsettings.Production.json'
$json | Set-Content -Path $prodSettings -Encoding utf8
# Confirm it parses.
$null = $json | ConvertFrom-Json

# --- 4. NTFS ACLs: grant the app-pool identity least privilege ----------------
Write-Step "Granting NTFS rights to $AppPoolIdentity"
function Grant-Ntfs($path, $rights) {
    $acl = Get-Acl $path
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $AppPoolIdentity, $rights, 'ContainerInherit,ObjectInherit', 'None', 'Allow')
    $acl.AddAccessRule($rule)
    Set-Acl -Path $path -AclObject $acl
}
Grant-Ntfs $SitePath 'ReadAndExecute'                       # app binaries: read/execute only
foreach ($d in $dataDirs) { Grant-Ntfs $d 'Modify' }        # stores the app reads/writes
# The app creates an App_Data folder under its content root at startup (Directory.CreateDirectory) and
# uses it for runtime scratch / data-protection keys. Pre-create it and grant Modify on just that folder,
# so the rest of the web root stays read-only. Without this the app throws at startup and IIS returns 500.
$siteAppData = Join-Path $SitePath 'App_Data'
New-Item -ItemType Directory -Force -Path $siteAppData | Out-Null
Grant-Ntfs $siteAppData 'Modify'
# Tighten the private signing key to the app identity (read) - provision the key out of band (OPERATIONS section 2).
$keysDir = Join-Path $DataRoot 'keys'
Write-Host "    (Provision $keysDir\seal-signing.pem out of band; do NOT let the app generate it in prod.)" -ForegroundColor Yellow

# --- 5. IIS: app pool + site + Windows Auth -----------------------------------
Write-Step "Configuring IIS (pool '$AppPoolName', site '$SiteName')"
Import-Module WebAdministration -ErrorAction Stop

if (-not (Test-Path "IIS:\AppPools\$AppPoolName")) { New-WebAppPool -Name $AppPoolName | Out-Null }
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name managedRuntimeVersion -Value ''      # No Managed Code
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name startMode -Value AlwaysRunning
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.idleTimeout -Value '00:00:00'
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.identityType -Value SpecificUser
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.userName -Value $AppPoolIdentity
if ($AppPoolCredential) {
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.password -Value $AppPoolCredential.GetNetworkCredential().Password
} else {
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.password -Value ''   # gMSA: no password
}

if (-not (Test-Path "IIS:\Sites\$SiteName")) {
    if ($CertificateThumbprint) {
        New-Website -Name $SiteName -PhysicalPath $SitePath -ApplicationPool $AppPoolName `
                    -HostHeader $Hostname -Port 443 -Ssl | Out-Null
        $binding = Get-WebBinding -Name $SiteName -Protocol https
        $binding.AddSslCertificate($CertificateThumbprint, 'My')
    } else {
        New-Website -Name $SiteName -PhysicalPath $SitePath -ApplicationPool $AppPoolName `
                    -HostHeader $Hostname -Port 80 | Out-Null
        Write-Host "    No cert supplied - created an HTTP binding. Put TLS in front or re-run with -CertificateThumbprint." -ForegroundColor Yellow
    }
} else {
    Set-ItemProperty "IIS:\Sites\$SiteName" -Name physicalPath -Value $SitePath
    Set-ItemProperty "IIS:\Sites\$SiteName" -Name applicationPool -Value $AppPoolName
}

# Windows Authentication on, Anonymous off. These sections are LOCKED at server scope by default, so the
# WebAdministration cmdlets throw 0x8007000D ("data is invalid") when targeting a site. appcmd with
# /commit:apphost writes a <location> entry into applicationHost.config, which the lock permits. Requires
# the Web-Windows-Auth role feature (Install-WindowsFeature Web-Windows-Auth -IncludeManagementTools).
$appcmd = Join-Path $env:WINDIR 'System32\inetsrv\appcmd.exe'
if (-not (Test-Path $appcmd)) { throw "appcmd.exe not found at $appcmd - is the IIS 'Web-Server' role installed?" }

$authSections = @(
    @{ Name = 'windowsAuthentication';   Enabled = 'true'  },
    @{ Name = 'anonymousAuthentication'; Enabled = 'false' }
)
foreach ($s in $authSections) {
    $out = & $appcmd set config "$SiteName" `
        "/section:system.webServer/security/authentication/$($s.Name)" `
        "/enabled:$($s.Enabled)" /commit:apphost 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw ("Failed to set $($s.Name) on '$SiteName' (appcmd exit $LASTEXITCODE): $out. Confirm the IIS " +
               "Windows Authentication role feature is installed (Install-WindowsFeature Web-Windows-Auth " +
               "-IncludeManagementTools) and that you are running elevated.")
    }
}

Restart-WebAppPool -Name $AppPoolName
Start-Website -Name $SiteName -ErrorAction SilentlyContinue

Write-Step "Install complete."
# Reflect the binding that was actually created (HTTPS only when a cert was supplied).
$scheme = if ($CertificateThumbprint) { 'https' } else { 'http' }
$baseUrl = "${scheme}://$Hostname/"
Write-Host @"

Next steps:
  1. Provision the integrity signing key out of band into:
        $keysDir\seal-signing.pem   (OPERATIONS.md section 2)
  2. Confirm SQL connectivity: the app applies EF migrations on first request/start.
        Browse to $baseUrl (the first request runs the SQL Server migrations).
  3. Verify:  .\Verify-Install.ps1 -Url $baseUrl -AppPoolName $AppPoolName
  4. Schedule the SQL backup + monthly restore-verification jobs (OPERATIONS.md section 1).
"@ -ForegroundColor Green
if (-not $CertificateThumbprint) {
    Write-Host "  Note: this is an HTTP binding. Add a TLS cert (or front it with TLS) before real case data." -ForegroundColor Yellow
}
