#Requires -Version 5.1
<#
.SYNOPSIS
    Provisions the CaseBook SQL Server 2022 database and the app-pool login (Windows auth).

.DESCRIPTION
    Wraps deploy/sql/01-Create-Database.sql. Creates the database (FULL recovery,
    RCSI on) and a least-privilege login/user for the IIS application-pool identity.
    Integrated authentication only - no SQL credentials are created or stored.

    Run on (or with line-of-sight to) the SQL Server, as an account that is sysadmin
    on the target instance. Idempotent - safe to re-run.

    Values can come from an answers file (-ConfigFile casebook.config.psd1, generated by
    New-CaseBookConfig.ps1) OR as parameters. A parameter you pass explicitly overrides
    the file.

.PARAMETER ConfigFile
    Path to a casebook.config.psd1 answers file (see casebook.config.template.psd1). Fills
    any parameter you don't pass explicitly. Optional - you can pass everything as parameters.

.PARAMETER SqlInstance
    Target instance, e.g. "SQLHOST" or "SQLHOST\INSTANCE". Required (parameter or config file).

.PARAMETER AppAccount
    Windows account the CaseBook IIS app pool runs as. For a gMSA include the
    trailing '$', e.g. "CONTOSO\svc-casebook$". Must already exist in AD.

.PARAMETER DbName
    Database name. Default: CaseBook.

.PARAMETER DataPath / LogPath
    Optional explicit folders for the data/log files. Omit to use instance defaults.

.PARAMETER SchemaMode
    AppMigrates (default) - grant db_owner; the app applies EF migrations at startup.
    DbaApplies             - grant datareader/datawriter/EXECUTE only; a DBA applies
                             the schema. Combine with -ApplySchema to run it now.

.PARAMETER ApplySchema
    When SchemaMode=DbaApplies, also execute deploy/sql/casebook-schema-sqlserver.sql
    against the database (as the sysadmin running this script).

.EXAMPLE
    .\Install-Database.ps1 -ConfigFile .\casebook.config.psd1

.EXAMPLE
    .\Install-Database.ps1 -SqlInstance SQLHOST\PROD -AppAccount "CONTOSO\svc-casebook$"
#>
[CmdletBinding()]
param(
    [string] $ConfigFile,
    [string] $SqlInstance,
    [string] $AppAccount,
    [string] $DbName,
    [string] $DataPath,
    [string] $LogPath,
    [ValidateSet('AppMigrates','DbaApplies')] [string] $SchemaMode,
    [switch] $ApplySchema
)

$ErrorActionPreference = 'Stop'

# --- Merge an optional answers file (explicit -Params win) --------------------
if ($ConfigFile) {
    if (-not (Test-Path $ConfigFile)) { throw "Config file not found: $ConfigFile" }
    $cfg = Import-PowerShellDataFile -Path $ConfigFile
    foreach ($name in 'SqlInstance','AppAccount','DbName','DataPath','LogPath','SchemaMode') {
        if (-not $PSBoundParameters.ContainsKey($name) -and $cfg.ContainsKey($name) -and "$($cfg[$name])" -ne '') {
            Set-Variable -Name $name -Value $cfg[$name]
        }
    }
}
# Defaults for anything still unset (built-in default is the lowest precedence).
if (-not $DbName)        { $DbName = 'CaseBook' }
if ($null -eq $DataPath) { $DataPath = '' }
if ($null -eq $LogPath)  { $LogPath  = '' }
if (-not $SchemaMode)    { $SchemaMode = 'AppMigrates' }
# Required, whichever source they came from.
$missing = @()
if (-not $SqlInstance) { $missing += 'SqlInstance' }
if (-not $AppAccount)  { $missing += 'AppAccount' }
if ($missing.Count) {
    throw "Missing required value(s): $($missing -join ', '). Pass as a -Parameter or set them in -ConfigFile (see casebook.config.template.psd1)."
}
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$createSql = Join-Path $scriptDir 'sql\01-Create-Database.sql'
$schemaSql = Join-Path $scriptDir 'sql\casebook-schema-sqlserver.sql'

if (-not (Test-Path $createSql)) { throw "Missing $createSql" }

# Pick an execution engine: prefer the SqlServer module's Invoke-Sqlcmd, fall back to sqlcmd.exe.
$useModule = $false
if (Get-Command Invoke-Sqlcmd -ErrorAction SilentlyContinue) {
    $useModule = $true
} elseif (-not (Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)) {
    throw "Neither the SqlServer PowerShell module (Invoke-Sqlcmd) nor sqlcmd.exe is available. " +
          "Install with:  Install-Module SqlServer -Scope CurrentUser"
}

function Invoke-Sql {
    param([string] $InputFile, [hashtable] $Vars, [switch] $NoDbVars)
    if ($useModule) {
        $varArray = $Vars.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }
        # -AbortOnError: Invoke-Sqlcmd ignores the script's ":on error exit", so without it a failed step (no
        # permission, say) was reported and the script carried on, printing success lines for things not done.
        Invoke-Sqlcmd -ServerInstance $SqlInstance -InputFile $InputFile -Variable $varArray `
                      -TrustServerCertificate -QueryTimeout 0 -OutputSqlErrors $true -AbortOnError -ErrorAction Stop -Verbose
    } else {
        $varArgs = @()
        foreach ($k in $Vars.Keys) { $varArgs += @('-v', ("{0}={1}" -f $k, $Vars[$k])) }
        & sqlcmd.exe -S $SqlInstance -E -b -C -i $InputFile @varArgs
        if ($LASTEXITCODE -ne 0) { throw "sqlcmd failed (exit $LASTEXITCODE) on $InputFile" }
    }
}

Write-Host "==> Provisioning database [$DbName] on [$SqlInstance] for [$AppAccount] (mode: $SchemaMode)" -ForegroundColor Cyan

# --- Preflight: does the account running this have the rights for what's still to do? ---------------------
# Creating the database needs CREATE ANY DATABASE (dbcreator), the server login ALTER ANY LOGIN (securityadmin),
# and the database user and its roles control of the database (its owner has that, so it follows from creating it).
# sysadmin has all of it. Checked first so a missing right stops here, before anything is half done.
$preflight = @"
SET NOCOUNT ON;
SELECT SUSER_SNAME() AS RunAs,
       IS_SRVROLEMEMBER('sysadmin') AS IsSysadmin,
       HAS_PERMS_BY_NAME(NULL, NULL, 'CREATE ANY DATABASE') AS CanCreateDb,
       HAS_PERMS_BY_NAME(NULL, NULL, 'ALTER ANY LOGIN') AS CanCreateLogin,
       CASE WHEN DB_ID(N'$($DbName -replace "'", "''")') IS NULL THEN 0 ELSE 1 END AS DbExists,
       CASE WHEN SUSER_ID(N'$($AppAccount -replace "'", "''")') IS NULL THEN 0 ELSE 1 END AS LoginExists,
       ISNULL(HAS_PERMS_BY_NAME(N'$($DbName -replace "'", "''")', 'DATABASE', 'CONTROL'), 0) AS ControlsDb;
"@
if ($useModule) {
    $p = Invoke-Sqlcmd -ServerInstance $SqlInstance -Query $preflight -TrustServerCertificate -AbortOnError -ErrorAction Stop
} else {
    $line = (& sqlcmd.exe -S $SqlInstance -E -b -C -h -1 -W -s '|' -Q $preflight) | Where-Object { $_ -match '\|' } | Select-Object -First 1
    if ($LASTEXITCODE -ne 0 -or -not $line) { throw "Couldn't connect to [$SqlInstance] to check permissions (sqlcmd exit $LASTEXITCODE)." }
    $f = $line.Split('|')
    $p = [pscustomobject]@{ RunAs = $f[0]; IsSysadmin = [int]$f[1]; CanCreateDb = [int]$f[2]; CanCreateLogin = [int]$f[3]
                            DbExists = [int]$f[4]; LoginExists = [int]$f[5]; ControlsDb = [int]$f[6] }
}
$lacking = @()
if ([int]$p.IsSysadmin -ne 1) {
    if ([int]$p.DbExists -eq 0 -and [int]$p.CanCreateDb -ne 1) { $lacking += "create the database [$DbName] (CREATE ANY DATABASE; the dbcreator role)" }
    if ([int]$p.LoginExists -eq 0 -and [int]$p.CanCreateLogin -ne 1) { $lacking += "create the login [$AppAccount] (ALTER ANY LOGIN; the securityadmin role)" }
    if ([int]$p.DbExists -eq 1 -and [int]$p.ControlsDb -ne 1) { $lacking += "add the user and its roles in the existing database [$DbName] (CONTROL on it; db_owner)" }
    # Server-level settings on the database (recovery model, snapshot isolation) need ALTER on it, which an owner has.
}
if ($lacking.Count) {
    throw ("[$($p.RunAs)] can't provision CaseBook on [$SqlInstance]: it isn't sysadmin and can't " + ($lacking -join '; or ') +
           ". Nothing was changed. Have a DBA with sysadmin run this script (same -ConfigFile), or grant those roles " +
           "for the install. See INSTALL.md section 2.")
}
Write-Host "    Running as [$($p.RunAs)]$(if ([int]$p.IsSysadmin -eq 1) { ' (sysadmin)' }): permissions OK." -ForegroundColor Gray

$vars = @{
    DbName     = $DbName
    AppAccount = $AppAccount
    DataPath   = $(if ($DataPath) { $DataPath } else { '(default)' })   # sqlcmd won't take an empty -v value
    LogPath    = $(if ($LogPath) { $LogPath } else { '(default)' })
    SchemaMode = $SchemaMode
}
Invoke-Sql -InputFile $createSql -Vars $vars

if ($SchemaMode -eq 'DbaApplies' -and $ApplySchema) {
    if (-not (Test-Path $schemaSql)) { throw "Missing $schemaSql (regenerate via deploy/README)" }
    Write-Host "==> Applying schema from $([System.IO.Path]::GetFileName($schemaSql))" -ForegroundColor Cyan
    if ($useModule) {
        Invoke-Sqlcmd -ServerInstance $SqlInstance -Database $DbName -InputFile $schemaSql `
                      -TrustServerCertificate -QueryTimeout 0 -OutputSqlErrors $true -AbortOnError -ErrorAction Stop
    } else {
        & sqlcmd.exe -S $SqlInstance -E -b -C -d $DbName -i $schemaSql
        if ($LASTEXITCODE -ne 0) { throw "sqlcmd failed applying schema (exit $LASTEXITCODE)" }
    }
}

Write-Host "==> Database provisioning complete." -ForegroundColor Green
if ($SchemaMode -eq 'AppMigrates') {
    Write-Host "    The schema is created automatically on the app's first start (EF migrations)." -ForegroundColor Gray
}
